name: PowerGem
version: 1.0.0
main: com.phantomsmp.powergem.PowerGemPlugin
api-version: '1.20'
commands:
  gem:
    description: Main command for PowerGem
    aliases: [powergem]
    permission: powergem.use
permissions:
  powergem.use:
    default: true
  powergem.admin:
    default: op